### ISSUE TITLE
Add a location name/description

### ISSUE THREAD

**Issue by joostschouppe** [thomersch/openstreetmap-calendar#1]
Currently there's just a mapmarker. But there might be several things at the location. So you might want to add a name as well. Optionally, it might be nice to add a description as well ("we hide behind the second cactus on the right"), though that can go in the general description as well.

**Comment by thomersch** [comment]
Agreed. We just have to think of an easy to use solution. Maybe an additional, optional text field that allows specifying a precise location?

**Comment by jbelien** [comment]
That's how I do (with Jekyll) for our OSMBE website: https://github.com/osmbe/website/blame/master/_events/en/2019-10-15-meeting-brussels.md#L7

But that's probably overcomplicating things :D

**Comment by thomersch** [comment]
> But that's probably overcomplicating things :D

I used to work on business process software, so I believe there is no layer of indirection that couldn't be extended with another layer of indirection ;)

Anyway, I fiddled around a bit

<img width="568" alt="Screenshot 2019-10-15 at 13 22 55" src="https://user-images.githubusercontent.com/948605/66827389-efbae000-ef4e-11e9-947f-5ca409954a17.png">

But it seems like there might be two pieces of information we would like to convey: First, just a location name (like in the screenshot) like "Cafe De Markten", and secondly additional info like "behind the cactus on the right".

It would make total sense to have the location name in the label, like "Cafe De Markten in Ville de Bruxelles, Brussels, Belgium", but showing "Cafe De Markten (behind the cactus on the right) in Ville de Bruxelles, Brussels, Belgium" seems excessive.

What do you think? Shall we limit to the brief location name (e.g. "Wikipedia Office") and additional info to find has to go into the text (e.g. "use the elevator to get into 3rd floor")? Or do we need to think further?

**Comment by joostschouppe** [comment]
I would opt for the simple solution.

**Comment by thomersch** [comment]
Ok, I'll finish my prototype with the simple location name. If issues arise in the future, we will need to reconsider.

**Comment by thomersch** [comment]
Deployed.

**Comment by jbelien** [comment]
Thanks @thomersch ! 🍾
