### ISSUE TITLE
Attend feature doesn't work

### ISSUE THREAD

**Issue by musuruan** [thomersch/openstreetmap-calendar#109]
Hi! 

The "attend" feature for an event on osmcal.org doesn't work. After you compile and submit the form you get: "Internal Error
Something went wrong, we recorded an error and will try to fix the issue as soon as possible."

Tested on:
https://osmcal.org/event/1538/

**Comment by thomersch** [comment]
Thanks for reporting!

It got indeed reported, `osmcal/forms.py:62` method `clean` seems to be the culprit. I'll look into it, it seems to be a regression.

**Comment by thomersch** [comment]
This seems to have it fixed. No idea how that ever worked, but now it does. Thanks again for reporting, and sorry for the inconvenience.

**Comment by musuruan** [comment]
Thank you!!
