### ISSUE TITLE
Duplicate action returns a 502

### ISSUE THREAD

**Issue by tordans** [thomersch/openstreetmap-calendar#129]
> Diese Seite funktioniert nicht
> osmcal.org kann diese Anfrage momentan nicht verarbeiten.
> HTTP ERROR 502

I tried to duplicate https://osmcal.org/event/2064/ but got an error 502 today (multiple times).

(FYI, I created https://osmcal.org/event/2065/ via the new-event-flow, which worked.)

**Comment by thomersch** [comment]
I think at that day we had some operational issues with the DB. The error tracking doesn't have any other indications. Please let me know, if you experience this issue again.
