### ISSUE TITLE
OSM Cal auto survey, cant pin loc, no manual timezone

### ISSUE THREAD

**Issue by mapbeks** [thomersch/openstreetmap-calendar#131]
![image](https://user-images.githubusercontent.com/17762042/235607228-881efa01-e710-4666-858b-7fad6a4ae154.png)

Greetings! 

I would like to just report that when I try  adding an event I can't seem to add the Timezone manually, add a pin on the map, and the survey section automatically appears and I cant remove it.

I tried reloading the page and the error seems to intermittently appear. Sometimes its there - sometimes not.

**Comment by thomersch** [comment]
Thanks for reporting, can confirm, the static assets don‘t always load. I reported this with the hosting provider: https://community.fly.io/t/statics-are-unreliable-since-migrating-to-v2/12651

**Comment by thomersch** [comment]
It got resolved by Fly, there seems to have been a configuration issue.

Thanks again for filing the issue!
