### ISSUE TITLE
Moderation

### ISSUE THREAD

**Issue by SherbetS44105** [thomersch/openstreetmap-calendar#134]
Hi Tom and team,

Recently, a [spam event ended up on osmcal](https://osmcal.org/event/2157). since this seems to have never been an issue in the past, given that I can't see any active moderators. I was wondering if there are tools available to delete events like these now and in the future as well.

Thanks,
-SherbetS (James Crawford)

**Comment by thomersch** [comment]
Actually, I found some time yesterday to write some code and now we have a better moderation mechanism, allowing us to hide spam. If this shouldn't suffice, we'll add more mods.

**Comment by tordans** [comment]
FYI, this spam event was created recently and I "cancelled" it https://osmcal.org/event/2683/
