### ISSUE TITLE
Wrong location saved when geocoded

### ISSUE THREAD

**Issue by jbelien** [thomersch/openstreetmap-calendar#14]
I created a [new event](https://osmcal.org/event/184/) today.
I looked for "Médecins Sans Frontières" in the "*Search for Location*" field but it located me in Geneva (instead of Belgium) so I moved manually the pin to the correct location in Brussels but when I saved the event, it saved the location in Geneva and not my manual location in Brussels.

**Comment by thomersch** [comment]
Yep, can reproduce. Gonna check this out.

**Comment by thomersch** [comment]
This whole leaflet draw integration is a bit weird. Even though editing was already allowed, the changes wouldn't automatically mutate the store. Now, there is an event listener that will do that. It's a bit weird, but apparently the use case of programmatically changing a marker is out of the ordinary.

Long story short: It should work now. Thanks for reporting 👍

**Comment by jbelien** [comment]
Thanks! 🎉 
I'll check with our next event !

**Comment by thomersch** [comment]
Great! I'll close the ticket for now :)
