### ISSUE TITLE
Use preferred tile.openstreetmap.org URL

### ISSUE THREAD

**Issue by danieldegroot2** [thomersch/openstreetmap-calendar#146]
I would like to suggest using the now preferred https://tile.openstreetmap.org URL instead of the current ones (a, b, c, etc.), see

https://github.com/openstreetmap/operations/issues/737

**Comment by thomersch** [comment]
They're coming from the django-leaflet library. It would probably make sense to upgrade this dependency, but I haven't checked whether they have changed the default to the non-abc domain. Also: OSMCAL has some glue code that controls the leaflet integration (for the create/edit event form), which needs to be tested to verify that the upgrade doesn't break anything.

There is probably some option to override the default tile layer, but I haven't looked that up.

**Comment by LaoshuBaby** [comment]
> They're coming from the django-leaflet library. It would probably make sense to upgrade this dependency, but I haven't checked whether they have changed the default to the non-abc domain.

Yes, it's from this library and I've checked they haven't make such kind of change. So I open this https://github.com/makinacorpus/django-leaflet/pull/375 PR just now

**Comment by thomersch** [comment]
Updating django-leaflet resolved the issue, thanks @LaoshuBaby for bringing this upsteam!
