### ISSUE TITLE
Nice to have : RSS date

### ISSUE THREAD

**Issue by beatnickgr** [thomersch/openstreetmap-calendar#149]
QuiteRSS 0.19.4 shows the publication date (it would make sense if I was reading the news).

Would be nice to have the date replaced with the event date, like I've seen it on another event feed, so it will be easier to sort.

**Comment by thomersch** [comment]
There is only the "pubDate" field in RSS (https://www.rssboard.org/rss-specification#ltpubdategtSubelementOfLtitemgt). The RSS documentation states that if that is in the future it may be omitted by the aggregators until that date, therefore I don't think it's a great fit for this use case.

**Comment by beatnickgr** [comment]
I have added a feed which is forked from https://paris.demosphere.net/
They give me the option to use the publication time or replace it with the event's time.
QuiteRSS is working fine with future dates and I haven't heard of any aggregator omitting them. 

If osmcal has nothing but pubDate it would be nice to at least have that date in the title, so that we don't open each and every post to check the event date.
