### ISSUE TITLE
Saving with location-pin returns HTTP 500 and shows Internal Error page

### ISSUE THREAD

**Issue by hauke96** [thomersch/openstreetmap-calendar#163]
I created event 2770 without location, because when adding a location, the HTTP request returns a 500 error and I see the "Internal Error" page.

After trying this in Chromium (instead of Firefox) it worked ... once. Now I also get the error page in Chromium when saving the event.

This is bad because the event is now kind of "locked" for me, I cannot edit a thing on it.

**Comment by danieldegroot2** [comment]
Worked properly once, then failed thereafter for the same event

This workflow only worked okay the first time(!)
1. Delete existing location
2. Save delete action
3. Search location 'Binnenalster'
4. Save event

**Comment by tordans** [comment]
I am getting an error 500 today after creating a duplicated event. (Multiple tries during the morning.)

> Internal Error
> Something went wrong, we recorded an error and will try to fix the issue as soon as possible.

```
Request URL:
https://osmcal.org/event/2734/duplicate/
Request Method:
POST
Status Code:
500 Internal Server Error
```

**Comment by thomersch** [comment]
Thanks for the reports!

From a quick look at it, it seems this happens when geocoding the location. Nominatim started to behave weirdly and sometimes returns a 403. I guess I'll have to implement some retrying mechanism to work around the unreliability.

**Comment by thomersch** [comment]
I've just deployed a fix - if geocoding fails, it's done in the background. The background system also has a retry/backoff mechanism, so it should geocode at some point.

Could y'all have a look whether it works as desired?

**Comment by hauke96** [comment]
Yes, works for me, thanks! :+1:
