### ISSUE TITLE
Attend button out of frame

### ISSUE THREAD

**Issue by danieldegroot2** [thomersch/openstreetmap-calendar#177]
The attend button now moves 'out of frame' into the footer ~~if the description (left column) is shorter than the actions (right column).~~ due to the map using the full column height (together with the action buttons below it).

Instance: osmcal.org
Browser: Chrome 126.0.6478.127 / 126.0.6478.183, Edge 126.0.2592.87 / 126.0.2592.102 / 126.0.2592.113, Firefox 127.0.2 / 128.0
OS: Windows 10
Regardless of logged in state or zoom. No errors returned.
_note, high dpp screen._

Short left column:
![image](https://github.com/user-attachments/assets/26386e32-8ccc-44f7-8f12-9d424e6ed570)

Long left column now returns extra tall map:
![image](https://github.com/user-attachments/assets/53f8d44b-f02a-472a-984c-850cc3f76f7c)

Ex. https://osmcal.org/event/2993/

**Comment by thomersch** [comment]
Looks like it's a new bug, possibly related to the updated Leaflet.

**Comment by danieldegroot2** [comment]
Thanks. Works properly on all mentioned browsers.
