### ISSUE TITLE
API can use `?around=<lat>,<lon>` just like website, missing in documentation

### ISSUE THREAD

**Issue by kmpoppe** [thomersch/openstreetmap-calendar#179]
In streetComplete/StreetComplete#1798, @westnordost thought about showing local events to users, if osmcal would issue lat/lon of an event (which it does), and I was wondering if the "Nearby" function from the website (`?around=<lat>,<lon>`) worked with the API.

It [works](https://osmcal.org/api/v2/events/?around=54.32148,10.12605) - showing the Kieler Linux Tage this weekend - yet the API documentation only says `?in=<iso3166-1 alpha-2>` was supported.

Is there a reason for omitting this parameter? Is it a fluke that it's working and not supposed to do?

**Comment by thomersch** [comment]
Moin!

All the event lists use the same query builder, and since we offer a nearby filter on the main page, the JSON and RSS feeds inherit the same functionality.

As to why it’s not documented, I commented on that before: https://github.com/thomersch/openstreetmap-calendar/issues/67#issuecomment-855425381

**Comment by kmpoppe** [comment]
Moin Thomas!

Thanks for pointing at the comment. I see where that's coming from and shall see if SC's option might be to figure out the around part in-app and thus only getting all the events and only show those matching.

**Comment by thomersch** [comment]
Feel free to use the `around` parameter, experience shows that the load is very manageable. If you could limit the decimal places of the coordinates that would be great, maybe to two or three. This allows for easier caching and preserves the user's privacy.

**Comment by kmpoppe** [comment]
Thanks :) Does `around` only take lat/lon or is there a ",radius" possibility like overpass can search objects around a position?

**Comment by thomersch** [comment]
It's hardcoded to a 50km radius at the moment

**Comment by kmpoppe** [comment]
Would you be open to parameterize that? I could try my hands on that ;)
