### ISSUE TITLE
Open a new tab by click on "Event website"

### ISSUE THREAD

**Issue by fredao** [thomersch/openstreetmap-calendar#2]
nft

**Comment by thomersch** [comment]
Thanks for reporting!

Not sure whether I want to force new tabs/windows onto all users. Especially on mobile this can be annoying to people. I'll look into the accessibility guideline for some guidance.

BTW: Can we get some coverage on Weekly OSM? ;)

**Comment by fredao** [comment]
[...]
> 
> BTW: Can we get some coverage on Weekly OSM? ;)
sure: best you write the text by yourself at least in DE or EN or even better in both
- because you know the app better than anybody else ;-)
https://osmbc.openstreetmap.de/

**Comment by qeef** [comment]
So... what does accessibility guidelines say? :)

**Comment by thomersch** [comment]
There is no rule on that, so I‘m leaving this to the users: Everyone can decide to open in a new window themselves.
