### ISSUE TITLE
Enable location filter on past events

### ISSUE THREAD

**Issue by jbelien** [thomersch/openstreetmap-calendar#23]
The location filter `?in=Belgium` doesn't seem to work for past events (ex. : https://osmcal.org/events/past/?in=Belgium)

**Comment by thomersch** [comment]
Yep, this makes sense. Probably also useful to have an API for past events, right?

**Comment by jbelien** [comment]
> Probably also useful to have an API for past events, right?

Would be awesome indeed! 🤩

**Comment by jbelien** [comment]
Hello,

I'll try to build some "widget" to integrate OSMCal to https://openstreetmap.be/.
Do you think you'll have time to implement the past events API (with location filter) ?
Thanks :)

**Comment by thomersch** [comment]
Sure, gonna work on it in the next days, as soon as I sort out the other bugs ;)

**Comment by thomersch** [comment]
We got an API: https://app.swaggerhub.com/apis-docs/osmcal/osmcal-api/1.0.1/

**Comment by jbelien** [comment]
B.E.A.U.T.I.F.U.L 🤩

**Comment by qeef** [comment]
I think this is already implemented, so it's possible to close the issue?

**Comment by jbelien** [comment]
Maybe something changed meanwhile but the filter doesn't seem to be applied : https://osmcal.org/events/past/?in=Belgium

**Comment by thomersch** [comment]
Ach, scheiße, how did that happen!? Will investigate.

**Comment by thomersch** [comment]
Fun fact: The past view did never get this feature.

Anyway, we got it now :)
