### ISSUE TITLE
Problem with duplicate (Repeat Event)

### ISSUE THREAD

**Issue by britiger** [thomersch/openstreetmap-calendar#26]
When I duplicate the event https://osmcal.org/event/229/ I have several "issues":
  - Fields of Start and End are only text fields => no calender to choose a date/time
  - A "Sign Up Survey" is created which was not on current event
    - I can't save because I need to enter a question

**Comment by thomersch** [comment]
Confirmed, thanks for reporting. Looks like a form JavaScript regression.

**Comment by thomersch** [comment]
This shall work now.

![osmcal-26](https://user-images.githubusercontent.com/948605/82153160-1d119880-9866-11ea-8bdf-62d654337b89.gif)
