### ISSUE TITLE
Links do not use HTTPS in API result

### ISSUE THREAD

**Issue by jbelien** [thomersch/openstreetmap-calendar#27]
When I fetch https://osmcal.org/api/v1/events/, I get

```json
{
  "name": "Online OpenStreetMap Foundation public board meeting",
  "url": "http://osmcal.org/event/235/",
  "date": {
    "human": "21st May 17:00", 
    "whole_day": false, 
    "start": "2020-05-21 17:00:00"
  },
  "location": {
    "short": null, 
    "detailed": null
  }
}
```

All the `url` links are using HTTP despite the fact I'm fetching HTTPS.

**Comment by thomersch** [comment]
Oh, yeah, damn… this looks like some issue with the reverse proxy configuration. Gonna look into it.

**Comment by thomersch** [comment]
Fixed :)

Because of my peculiar setup, which layers nginx on nginx, the first one was writing `https` into `X-Forwarded-Proto` and the second was overwriting this with `http`.
