### ISSUE TITLE
Smth wrong with select on mobile

### ISSUE THREAD

**Issue by Semigradsky** [thomersch/openstreetmap-calendar#3]
![Screenshot_2019-11-25-09-05-28-810_com android chrome](https://user-images.githubusercontent.com/1198848/69516517-e9168400-0f62-11ea-882c-688bb69006c0.png)

**Comment by thomersch** [comment]
Thanks for the report. What browser/OS version are using?

Sometimes there are issues with rendering the select dropdown on Firefox, which may be a combination of the custom font and dropdown icon.

**Comment by Semigradsky** [comment]
Android 7.1.2; Redmi 4X
Chrome 78.0.3904.108

**Comment by thomersch** [comment]
I just shipped a patch to the SVG file, which was broken on Firefox 70 and looks fine now. Thanks @britiger for helping!

@Semigradsky can you verify if it looks good on your side?

**Comment by Semigradsky** [comment]
Yeah, it looks good now! 👍
