### ISSUE TITLE
✨ Widget

### ISSUE THREAD

**Issue by jbelien** [thomersch/openstreetmap-calendar#31]
As promised, I'm working on a widget: https://github.com/jbelien/openstreetmap-calendar-widget

**Features:**

- Events list (past/future)
- Events map (past/future)
- Events calendar (future)
- Filter by Country
- Limit number of results
- Custom template

You can have a look at the demo here: https://osmcal-widget.netlify.app/demo.html

**Comment by thomersch** [comment]
Awesome! 💪

**Comment by jbelien** [comment]
✨ New feature: Widget Calendar !

Still needs some work : 
- https://github.com/jbelien/openstreetmap-calendar-widget/issues/1
- https://github.com/jbelien/openstreetmap-calendar-widget/issues/2 (suggestions are welcome for this one)

**Comment by jbelien** [comment]
Widget released 🎉 

- https://www.npmjs.com/package/openstreetmap-calendar-widget
- https://unpkg.com/openstreetmap-calendar-widget@0.1.0/dist/osmcal.js

**Comment by jbelien** [comment]
Full documentation: https://github.com/jbelien/openstreetmap-calendar-widget#readme

**Comment by thomersch** [comment]
Mentioned in docs: https://osmcal.org/documentation/#Integrations

**Comment by qeef** [comment]
I mentioned the widget in #38, can this issue be closed?
