### ISSUE TITLE
Locale aware date formatting in API

### ISSUE THREAD

**Issue by thomersch** [thomersch/openstreetmap-calendar#33]
The website is obviously english only at the moment, but for the API it would be really good to have localized dates, so integrations into local websites would be easier.

**Comment by thomersch** [comment]
Ok, so we'll do it the same way as @jbelien: HTTP Accept-Language awareness, overridable using GET-parameter

**Comment by jbelien** [comment]
Works like a charm 🤩

**Comment by thomersch** [comment]
Since `Accept-Language` should be controllable everywhere, we‘re sticking to this. We‘re done here 😊
