### ISSUE TITLE
Cannot authenticate to osm.org from localhost

### ISSUE THREAD

**Issue by qeef** [thomersch/openstreetmap-calendar#39]
After exporting local variables with osm key and secret, I still have problem with authentication to osm.org. function `oauth_callback` is not even called (I tested it with `printf`).

I want to ask if there is something yet to set up than pull request #38 and osm key and secret env. variables?

**Comment by thomersch** [comment]
So, you've created an OAuth client on osm.org and added your key and secret to `OSMCAL_OSM_KEY` and `OSMCAL_OSM_SECRET`, right?

osm.org will redirect back to osmcal after successful login. For this purpose the “Callback URL” has to be configured correctly. For me (hosting locally with default settings) it looks like this:

<img width="436" alt="Screenshot 2020-06-24 at 11 56 01" src="https://user-images.githubusercontent.com/948605/85534851-f89d9e80-b611-11ea-9e4c-c9c0068b5f09.png">

**Comment by qeef** [comment]
That would be the problem. I didn't set callback URL (I did it programatically in my another project). I will test it today evening and close the issue asap. Thanks.
