### ISSUE TITLE
Duplicate maintainance work on Wiki OSM & OSMCal openstreetmap-calendar

### ISSUE THREAD

**Issue by Binnette** [thomersch/openstreetmap-calendar#43]
Hi, should we consider https://osmcal.org/ as the only reference to events OR consider https://wiki.openstreetmap.org/wiki/Current_events as the only reference?

The issue is that osmcal.org duplicate the work load. Cause I need to edit the wiki AND osmcal to register my event.

Is there any solution? Have a nice day.

**Comment by thomersch** [comment]
Yes, I absolutely agree. The integration of osmcal into the wiki is currently work in progress: https://github.com/openstreetmap/chef/pull/350

**Comment by thomersch** [comment]
Switchover is currently being planned: https://github.com/thomersch/OSMCALWikiWidget/issues/3

**Comment by thomersch** [comment]
The wiki calendar has been replaced.
