### ISSUE TITLE
Unrecognized Time Zone

### ISSUE THREAD

**Issue by thomersch** [thomersch/openstreetmap-calendar#47]
A user added an event in the time zone "US/Mountain", which is a valid selection, but this lead to an error at database level:

    time zone "US/Mountain" not recognized

This does look like an incompatibility between time databases. Maybe it is just an operational issue.

**Comment by thomersch** [comment]
The dropdown in the event form comes from pytz, who say:

> [...] It doesn’t contain deprecated zones or historical zones, except for a few I’ve deemed in common usage, such as US/Eastern 

Anyhow, the timezone DB that PostgreSQL uses is a IANA dump, which does not include deprecated time zones (such as US/Mountain, US/Eastern etc).

**Comment by thomersch** [comment]
Timezones are now converted into "Continent/Place" format and displayed as timezone name.

**Comment by danieldegroot2** [comment]
@thomersch Site returns Server Error (500) again; may be related.
