### ISSUE TITLE
Error 500 : Due to US/Eastern timezone ?

### ISSUE THREAD

**Issue by jbelien** [thomersch/openstreetmap-calendar#48]
I was adding the [4 MSF mapathons](https://www.doctorswithoutborders.org/take-action/attend-event/msf-geo-week-global-mapathons) to <https://osmcal.org/>.

When I save the last one, I had a `Server Error (500)` that's here since.
Last thing that was different than the events I usually add was the timezone, I chose `US/Eastern`.

**Comment by thomersch** [comment]
Aye, same as #47. The drop down in the event creation lists deprecated time zones such as “US/Eastern“, but then the database query fails, because PostgreSQL doesn‘t know them anymore.

**Comment by jbelien** [comment]
Duplicate of #47 .
Sorry for the noise.
