### ISSUE TITLE
Map stylesheet out of whack?

### ISSUE THREAD

**Issue by grischard** [thomersch/openstreetmap-calendar#52]
![image](https://user-images.githubusercontent.com/1556567/100891049-289e7700-34b9-11eb-86f3-9cd37cb8e16f.png)

Google Chrome 87.0.4280.67, macOS Big Sur.

**Comment by thomersch** [comment]
Looks crappy in Firefox, too. Probably some side effect of the form stylesheet onto the map plugin.

**Comment by thomersch** [comment]
Fixed:

<img width="521" alt="Screenshot 2020-12-03 at 14 39 07" src="https://user-images.githubusercontent.com/948605/101025098-59dc7d00-3575-11eb-8d32-73877585ba65.png">
