### ISSUE TITLE
Help to CREATE USER DATABASE ROLE

### ISSUE THREAD

**Issue by pyrog** [thomersch/openstreetmap-calendar#54]
Hi,

I try to run omscal locally but it seem that some steps are missing in README.md.

- **Docker**
The port seem not published.
Option `--publish 5432:5432` should be added to `docker run`command ?

- **Local Installation**
Could you explain exactly how to create database, user and role ?

Thank you.

PS: I run osmcal on macOS

**Comment by thomersch** [comment]
Should be resolved by https://github.com/thomersch/openstreetmap-calendar/commit/83707e90941f1e3a4502d3d692e34c537ebbd02e
