### ISSUE TITLE
Show "open end" events as upcoming or current after begin

### ISSUE THREAD

**Issue by britiger** [thomersch/openstreetmap-calendar#59]
The last meetup I created has started 19:00, due to current situation this event was online. I don't define an end for this event, because it's open end. Usually a part of the participants are coming after the beginning. 
So I defined a event without end this is moving to past events after beginning. You can't find the event in osm wiki widget to get the link to the video conference page or if you want to look where is the correct house number of physical meetups. You need to go to osmcal.org and check the past events.

Solution:
A event without a end date and time should shown as upcoming or current event 1 or 2 hours after beginning or like discussed on Berlin meetup last week until end of day.

**Comment by thomersch** [comment]
Good point! I remember that something like this crossed my mind a while ago, but it never made it.

End of day sounds like a very good idea. This should prevent a lot of edge cases and is even better for database performance ;)
