### ISSUE TITLE
Calendar Subscription

### ISSUE THREAD

**Issue by adrienandrem** [thomersch/openstreetmap-calendar#6]
What I've been missing from the Wiki events is the possibility to add it to a calendar.

I would be great if we could connect a `CalDAV` client to OSMCal.  
for example, with the following URL:  
`https://osmcal.org/events.ics/?in=Country`

**Comment by thomersch** [comment]
Thanks for reporting.

There is the option to add single events to your calendar via ics:
<img width="1127" alt="Screenshot 2019-12-18 at 13 37 05" src="https://user-images.githubusercontent.com/948605/71087221-f3abee00-219b-11ea-9605-f772724d4d01.png">

> CalDAV client

I don't think CalDAV is what you want: You want a plain http-based calendar subscription via iCal files. This is a thing I definitely want to integrate, I just have to code it.

**Comment by thomersch** [comment]
Ok, so I hacked something together.

It works at least in Calendar on macOS, can you also check it out, @adrienandrem and @jbelien? The URL is https://osmcal.org/events.ics. You can append a filter, like on the homepage, e.g. https://osmcal.org/events.ics?in=France

If it works in your software, we can make an announcement for it.

**Comment by jbelien** [comment]
Seems to work just fine! 👌 🎉 
(tested in Fastmail Calendar)

I guess it's on purpose but there is only future events (not past events).

**Comment by joto** [comment]
Looks good to me!

**Comment by thomersch** [comment]
Phew, that was quick. Thanks for testing!

> I guess it's on purpose but there is only future events (not past events).

I haven't really put too much thought into it, I just inherited the other feeds' behaviour. Probably I would make sense to go a few weeks back or something...? What do you think?

**Comment by jbelien** [comment]
> I haven't really put too much thought into it, I just inherited the other feeds' behaviour. Probably I would make sense to go a few weeks back or something...? What do you think?

Indeed, no need to go wayyy back but a few weeks back seems useful :)

**Comment by thomersch** [comment]
Ok, events now go by 30 days back in the feed.

**Comment by adrienandrem** [comment]
Excellent! Tested in Thunderbird Lightning

'not used to features developed so quickly! Thank you!

**Comment by urbanhop** [comment]
works perfectly in outlook 2013 as well.
