### ISSUE TITLE
Delete or hide events

### ISSUE THREAD

**Issue by britiger** [thomersch/openstreetmap-calendar#62]
Since solve #24 it is possible to cancel events. But currently I found  some events which created accidentality twice so one of them was cancelled. We also had created second entry for an event by we found a way to reuse the event for another entry.

To avoid this confusing events it should be possible to hide or delete events.

**Comment by thomersch** [comment]
I introduced the possibility to hide events, but this is currently only available for moderators. We could extend this to the original creator of the event.

**Comment by thomersch** [comment]
The original creator may also hide their own events now.
