### ISSUE TITLE
Change map attribution link to HTTPS

### ISSUE THREAD

**Issue by danieldegroot2** [thomersch/openstreetmap-calendar#90]
Change from
http://www.openstreetmap.org/copyright
to
https://www.openstreetmap.org/copyright

![image](https://user-images.githubusercontent.com/67521919/154122312-9b6f98e3-5ec8-42a3-9aa9-95e12298ed43.png)

**Comment by thomersch** [comment]
Sure, makes sense.

This comes from [django-leaflet](https://github.com/makinacorpus/django-leaflet). We can override this locally in osmcal, but probably it'd make sense to fix it there directly: https://github.com/makinacorpus/django-leaflet/blob/b9ed86fc457ca0861717a780d784f0735de4c26c/leaflet/__init__.py#L13

Maybe you could open an issue over there?

**Comment by danieldegroot2** [comment]
PR has been merged, should eventually be fixed.

**Comment by thomersch** [comment]
Great, thanks!
